<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__ . '/src')
    ->in(__DIR__ . '/core')
    ->in(__DIR__ . '/includes')
    ->in(__DIR__ . '/ai')
    ->in(__DIR__ . '/api')
    ->notPath('vendor')
    ->notPath('tests')
    ->notPath('logs')
    ->notPath('uploads')
    ->notPath('cache')
    ->notPath('backups');

return (new PhpCsFixer\Config())
    ->setRules([
        '@PSR12' => true,
        '@PHP80Migration' => true,
        '@PHP81Migration' => true,
        '@PHPUnit84Migration:risky' => true,
        '@DoctrineAnnotation' => true,
        '@Symfony:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'binary_operator_spaces' => true,
        'blank_line_after_opening_tag' => true,
        'blank_line_before_statement' => [
            'statements' => ['break', 'continue', 'declare', 'return', 'throw', 'try'],
        ],
        'braces' => true,
        'cast_spaces' => true,
        'class_definition' => [
            'single_line' => false,
            'multi_line_extends_each_single_line' => true,
        ],
        'concat_space' => ['spacing' => 'one'],
        'declare_equal_spaces' => true,
        'declare_strict_types' => true,
        'elseif' => true,
        'encoding' => true,
        'full_opening_tag' => true,
        'fully_qualified_strict_types' => true,
        'function_declaration' => [
            'closure_function_spacing' => 'none',
            'return_type_spacing' => 'one',
        ],
        'function_typehint_space' => true,
        'heredoc_indentation' => true,
        'include' => true,
        'increment_style' => ['style' => 'post'],
        'indentation_type' => true,
        'is_null' => true,
        'line_ending' => true,
        'list_syntax' => ['syntax' => 'short'],
        'logical_operators' => true,
        'lowercase_cast' => true,
        'lowercase_keywords' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'method_argument_space' => [
            'on_multiline' => 'ensure_fully_multiline',
            'keep_multiple_spaces' => false,
        ],
        'method_chaining_indentation' => true,
        'modernize_types_casting' => true,
        'multiline_whitespace_before_semicolons' => true,
        'native_function_casing' => true,
        'native_function_invocation' => [
            'include' => ['@internal'],
            'scope' => 'all',
            'strict' => true,
        ],
        'new_with_braces' => true,
        'no_alternative_syntax' => true,
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc' => true,
        'no_closing_tag' => true,
        'no_empty_comment' => true,
        'no_empty_phpdoc' => true,
        'no_extra_blank_lines' => [
            'tokens' => [
                'curly_brace_open',
                'curly_brace_close',
                'extra',
                'parenthesis_brace_open',
                'parenthesis_brace_close',
                'square_brace_open',
                'square_brace_close',
                'use',
                'use_trait',
                'switch',
                'case',
                'default',
                'break',
                'continue',
                'return',
                'throw',
                'try',
                'catch',
                'finally',
                'endif',
                'endfor',
        'endforeach',
        'endwhile',
        'enddeclare',
    ],
],
'no_empty_statement' => true,
'no_leading_import_slash' => true,
'no_leading_namespace_whitespace' => true,
'no_mixed_echo_print' => true,
'no_multiline_whitespace_around_double_arrow' => true,
'no_short_bool_cast' => true,
'no_singleline_whitespace_before_semicolons' => true,
'no_spaces_after_function_name' => true,
'no_spaces_around_offset' => true,
'no_spaces_inside_parentheses' => true,
'no_superfluous_elseif' => true,
'no_trailing_comma_in_list_call' => true,
'no_trailing_comma_in_singleline_array' => true,
'no_trailing_whitespace' => true,
'no_unneeded_control_parentheses' => true,
'no_unneeded_curly_braces' => true,
'no_unneeded_import_alias' => true,
'no_unset_cast' => true,
'no_unused_imports' => true,
'no_whitespace_before_comma_in_array' => true,
'no_whitespace_in_blank_line' => true,
'non_printing_character' => true,
'normalize_index_brace' => true,
'object_operator_without_whitespace' => true,
'ordered_class_elements' => [
    'order' => [
        'use_trait',
        'case',
        'default',
        'public',
        'protected',
        'private',
        'constant',
        'property',
        'method',
    ],
],
'ordered_imports' => [
    'imports_order' => ['class', 'function', 'const'],
],
'php_unit_fqcn_annotation' => true,
'php_unit_internal_class' => false,
'php_unit_method_casing' => true,
'phpdoc_align' => true,
'phpdoc_annotation_without_dot' => true,
'phpdoc_indent' => true,
'phpdoc_inline_tag_normalizer' => true,
'phpdoc_no_access' => true,
'phpdoc_no_alias_tag' => true,
'phpdoc_no_empty_return' => true,
'phpdoc_no_package' => true,
'phpdoc_order' => true,
'phpdoc_scalar_type' => true,
'phpdoc_separation' => true,
'phpdoc_single_line_var_spacing' => true,
'phpdoc_summary' => true,
'phpdoc_to_comment' => true,
'phpdoc_trim' => true,
'phpdoc_types' => true,
'phpdoc_types_order' => [
    'null',
    'bool',
    'int',
    'float',
    'string',
    'array',
    'object',
    'callable',
    'resource',
],
'pow_to_exponentiation' => true,
'protected_to_private' => true,
'return_type_declaration' => true,
'self_namespace' => true,
'semicolon_after_instruction' => true,
'short_scalar_cast' => true,
'single_blank_line_at_eof' => true,
'single_class_element_per_statement' => true,
'single_import_per_statement' => true,
'single_line_after_imports' => true,
'single_line_comment_style' => [
    'comment_types' => ['hash'],
],
'single_quote' => true,
'space_after_semicolon' => true,
'space_before_semicolon' => true,
'spaces_inside_parentheses' => true,
'standardize_not_equals' => true,
'strict_comparison' => true,
'switch_case_semicolon_to_colon' => true,
'ternary_operator_spaces' => true,
'trailing_comma_in_multiline' => true,
'trim_array_spaces' => true,
'type_declaration_spaces' => [
    'elements' => ['function', 'method', 'property'],
],
'unary_operator_spaces' => true,
'visibility_required' => [
    'elements' => ['method', 'property'],
],
'whitespace_after_comma_in_array' => true,
'yoda_style' => true,
])
    ->setFinder($finder)
    ->setUsingCache(true)
    ->setCacheFile(__DIR__ . '/.php-cs-fixer.cache');
