<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/database.php';

class AIDocumentationEngine
{
    private $tenantId;
    private $userId;

    public function __construct($userId = null, $tenantId = null)
    {
        $this->userId = $userId ?? ($_SESSION['user_id'] ?? 0);
        $this->tenantId = $tenantId ?? ($_SESSION['tenant_id'] ?? 1);
    }

    /**
     * Generate PDF document from dashboard content
     */
    public function generatePDF($title, $content, $metadata = [])
    {
        try {
            $documentId = $this->createDocumentRecord($title, 'pdf', $content, $metadata);

            // Generate PDF using TCPDF or similar library
            $pdfContent = $this->createPDFContent($title, $content, $metadata);

            // Save PDF file
            $filePath = $this->saveDocumentFile($documentId, $pdfContent, 'pdf');

            // Update document record with file path
            $this->updateDocumentFile($documentId, $filePath);

            return [
                'success' => true,
                'document_id' => $documentId,
                'file_path' => $filePath,
                'download_url' => "/attendance/docs/download.php?id=" . $documentId
            ];
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::generatePDF error: " . $e->getMessage());
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Generate DOCX document from dashboard content
     */
    public function generateDOCX($title, $content, $metadata = [])
    {
        try {
            $documentId = $this->createDocumentRecord($title, 'docx', $content, $metadata);

            // Generate DOCX content
            $docxContent = $this->createDOCXContent($title, $content, $metadata);

            // Save DOCX file
            $filePath = $this->saveDocumentFile($documentId, $docxContent, 'docx');

            // Update document record with file path
            $this->updateDocumentFile($documentId, $filePath);

            return [
                'success' => true,
                'document_id' => $documentId,
                'file_path' => $filePath,
                'download_url' => "/attendance/docs/download.php?id=" . $documentId
            ];
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::generateDOCX error: " . $e->getMessage());
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Create document record in database
     */
    private function createDocumentRecord($title, $type, $content, $metadata)
    {
        try {
            $documentId = db()->insert('ai_documents', [
                'tenant_id' => $this->tenantId,
                'user_id' => $this->userId,
                'title' => $title,
                'type' => $type,
                'content' => json_encode($content),
                'metadata' => json_encode($metadata),
                'status' => 'processing',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]);

            return $documentId;
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::createDocumentRecord error: " . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Create PDF content
     */
    private function createPDFContent($title, $content, $metadata)
    {
        // For now, create a simple HTML-based PDF
        // In production, use a proper PDF library like TCPDF or DomPDF

        $html = $this->generateDocumentHTML($title, $content, $metadata);

        // Convert HTML to PDF (simplified approach)
        // In production, this would use a proper PDF generation library
        $pdfContent = "<!DOCTYPE html>
<html>
<head>
    <title>{$title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .content { line-height: 1.6; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class='header'>
        <h1>{$title}</h1>
        <p>Generated on " . date('Y-m-d H:i:s') . "</p>
    </div>
    <div class='content'>
        {$html}
    </div>
    <div class='footer'>
        <p>Generated by " . APP_NAME . " AI Documentation Engine</p>
    </div>
</body>
</html>";

        return $pdfContent;
    }

    /**
     * Create DOCX content
     */
    private function createDOCXContent($title, $content, $metadata)
    {
        // For now, create a simple HTML-based DOCX
        // In production, use a proper DOCX library like PHPWord

        $html = $this->generateDocumentHTML($title, $content, $metadata);

        // Create DOCX content (simplified approach)
        $docxContent = "<!DOCTYPE html>
<html>
<head>
    <title>{$title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .content { line-height: 1.6; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class='header'>
        <h1>{$title}</h1>
        <p>Generated on " . date('Y-m-d H:i:s') . "</p>
    </div>
    <div class='content'>
        {$html}
    </div>
    <div class='footer'>
        <p>Generated by " . APP_NAME . " AI Documentation Engine</p>
    </div>
</body>
</html>";

        return $docxContent;
    }

    /**
     * Generate document HTML
     */
    private function generateDocumentHTML($title, $content, $metadata)
    {
        $html = "<h2>{$title}</h2>";

        if (is_array($content)) {
            foreach ($content as $section) {
                if (isset($section['title'])) {
                    $html .= "<h3>" . htmlspecialchars($section['title']) . "</h3>";
                }
                if (isset($section['content'])) {
                    $html .= "<p>" . nl2br(htmlspecialchars($section['content'])) . "</p>";
                }
                if (isset($section['items']) && is_array($section['items'])) {
                    $html .= "<ul>";
                    foreach ($section['items'] as $item) {
                        $html .= "<li>" . nl2br(htmlspecialchars($item)) . "</li>";
                    }
                    $html .= "</ul>";
                }
            }
        } else {
            $html .= "<p>" . nl2br(htmlspecialchars($content)) . "</p>";
        }

        // Add metadata
        if (!empty($metadata)) {
            $html .= "<h3>Document Information</h3>";
            $html .= "<ul>";
            foreach ($metadata as $key => $value) {
                $html .= "<li><strong>" . htmlspecialchars(ucfirst(str_replace('_', ' ', $key))) . ":</strong> " . nl2br(htmlspecialchars($value)) . "</li>";
            }
            $html .= "</ul>";
        }

        return $html;
    }

    /**
     * Save document file
     */
    private function saveDocumentFile($documentId, $content, $type)
    {
        try {
            // Create docs directory if it doesn't exist
            $docsDir = __DIR__ . '/../docs';
            if (!is_dir($docsDir)) {
                mkdir($docsDir, 0755, true);
            }

            // Generate filename
            $filename = "document_{$documentId}_" . date('Y-m-d_H-i-s') . ".{$type}";
            $filePath = $docsDir . '/' . $filename;

            // Save file
            file_put_contents($filePath, $content);

            return $filename;
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::saveDocumentFile error: " . $e->getMessage());
            throw $e;
        }
    }

    /**
     * Update document file record
     */
    private function updateDocumentFile($documentId, $filePath)
    {
        try {
            db()->update('ai_documents', [
                'file_path' => $filePath,
                'status' => 'completed',
                'updated_at' => date('Y-m-d H:i:s')
            ], 'id = ?', [$documentId]);
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::updateDocumentFile error: " . $e->getMessage());
        }
    }

    /**
     * Get document list
     */
    public function getDocuments($limit = 50, $offset = 0)
    {
        try {
            return db()->fetchAll("
                SELECT d.*, u.first_name, u.last_name, u.role
                FROM ai_documents d
                JOIN users u ON d.user_id = u.id
                WHERE d.tenant_id = ?
                ORDER BY d.created_at DESC
                LIMIT ? OFFSET ?
            ", [$this->tenantId, $limit, $offset]);
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::getDocuments error: " . $e->getMessage());
            return [];
        }
    }

    /**
     * Get document by ID
     */
    public function getDocument($documentId)
    {
        try {
            return db()->fetchOne("
                SELECT d.*, u.first_name, u.last_name, u.role
                FROM ai_documents d
                JOIN users u ON d.user_id = u.id
                WHERE d.id = ? AND d.tenant_id = ?
            ", [$documentId, $this->tenantId]);
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::getDocument error: " . $e->getMessage());
            return null;
        }
    }

    /**
     * Generate dashboard report
     */
    public function generateDashboardReport($dashboardType, $filters = [])
    {
        try {
            $title = ucfirst($dashboardType) . " Dashboard Report";

            // Get dashboard data based on type
            $content = $this->getDashboardData($dashboardType, $filters);

            $metadata = [
                'dashboard_type' => $dashboardType,
                'generated_by' => $this->userId,
                'filters' => $filters,
                'generation_date' => date('Y-m-d H:i:s')
            ];

            return $this->generatePDF($title, $content, $metadata);
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::generateDashboardReport error: " . $e->getMessage());
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * Get dashboard data
     */
    private function getDashboardData($dashboardType, $filters)
    {
        $content = [];

        switch ($dashboardType) {
            case 'admin':
                $content = $this->getAdminDashboardData($filters);
                break;
            case 'teacher':
                $content = $this->getTeacherDashboardData($filters);
                break;
            case 'student':
                $content = $this->getStudentDashboardData($filters);
                break;
            case 'parent':
                $content = $this->getParentDashboardData($filters);
                break;
            case 'accountant':
                $content = $this->getAccountantDashboardData($filters);
                break;
            case 'librarian':
                $content = $this->getLibrarianDashboardData($filters);
                break;
            case 'transport':
                $content = $this->getTransportDashboardData($filters);
                break;
            default:
                $content = ['title' => 'Unknown Dashboard', 'content' => 'No data available'];
        }

        return $content;
    }

    /**
     * Get admin dashboard data
     */
    private function getAdminDashboardData($filters)
    {
        $dateRange = $filters['date_range'] ?? '7 days';

        $stats = db()->fetchOne("
            SELECT
                COUNT(DISTINCT u.id) as total_users,
                COUNT(DISTINCT CASE WHEN u.role = 'student' THEN u.id END) as total_students,
                COUNT(DISTINCT CASE WHEN u.role = 'teacher' THEN u.id END) as total_teachers,
                COUNT(DISTINCT CASE WHEN u.role = 'parent' THEN u.id END) as total_parents,
                COUNT(DISTINCT c.id) as total_classes,
                COUNT(DISTINCT ar.id) as total_attendance_records
            FROM users u
            LEFT JOIN classes c ON u.tenant_id = c.tenant_id
            LEFT JOIN attendance_records ar ON u.tenant_id = ar.tenant_id
            WHERE u.tenant_id = ? AND u.status = 'active'
        ", [$this->tenantId]);

        return [
            [
                'title' => 'System Overview',
                'content' => "Total Users: {$stats['total_users']}\nStudents: {$stats['total_students']}\nTeachers: {$stats['total_teachers']}\nParents: {$stats['total_parents']}\nClasses: {$stats['total_classes']}\nAttendance Records: {$stats['total_attendance_records']}"
            ],
            [
                'title' => 'System Health',
                'content' => "System is operating normally. All modules are active and functioning properly."
            ]
        ];
    }

    /**
     * Get teacher dashboard data
     */
    private function getTeacherDashboardData($filters)
    {
        $teacherId = $filters['teacher_id'] ?? $this->userId;

        $stats = db()->fetchOne("
            SELECT
                COUNT(DISTINCT c.id) as total_classes,
                COUNT(DISTINCT ce.student_id) as total_students,
                COUNT(DISTINCT ar.id) as total_attendance_records,
                AVG(CASE WHEN ar.status = 'present' THEN 1 ELSE 0 END) as attendance_rate
            FROM classes c
            LEFT JOIN class_enrollments ce ON c.id = ce.class_id
            LEFT JOIN attendance_records ar ON c.id = ar.class_id
            WHERE c.class_teacher_id = ? AND c.tenant_id = ?
        ", [$teacherId, $this->tenantId]);

        return [
            [
                'title' => 'Teaching Overview',
                'content' => "Classes: {$stats['total_classes']}\nStudents: {$stats['total_students']}\nAttendance Records: {$stats['total_attendance_records']}\nAverage Attendance Rate: " . round($stats['attendance_rate'] * 100, 1) . "%"
            ]
        ];
    }

    /**
     * Get student dashboard data
     */
    private function getStudentDashboardData($filters)
    {
        $studentId = $filters['student_id'] ?? $this->userId;

        $stats = db()->fetchOne("
            SELECT
                COUNT(DISTINCT ce.class_id) as total_classes,
                COUNT(DISTINCT ar.id) as total_attendance_records,
                AVG(CASE WHEN ar.status = 'present' THEN 1 ELSE 0 END) as attendance_rate,
                AVG(g.grade) as average_grade
            FROM users u
            LEFT JOIN class_enrollments ce ON u.id = ce.student_id
            LEFT JOIN attendance_records ar ON u.id = ar.student_id
            LEFT JOIN grades g ON u.id = g.student_id
            WHERE u.id = ? AND u.tenant_id = ?
        ", [$studentId, $this->tenantId]);

        return [
            [
                'title' => 'Academic Overview',
                'content' => "Classes: {$stats['total_classes']}\nAttendance Records: {$stats['total_attendance_records']}\nAttendance Rate: " . round($stats['attendance_rate'] * 100, 1) . "%\nAverage Grade: " . round($stats['average_grade'], 1)
            ]
        ];
    }

    /**
     * Get parent dashboard data
     */
    private function getParentDashboardData($filters)
    {
        $parentId = $filters['parent_id'] ?? $this->userId;

        $stats = db()->fetchOne("
            SELECT
                COUNT(DISTINCT psl.student_id) as total_children,
                COUNT(DISTINCT ar.id) as total_attendance_records,
                AVG(CASE WHEN ar.status = 'present' THEN 1 ELSE 0 END) as attendance_rate,
                AVG(g.grade) as average_grade
            FROM users u
            LEFT JOIN parent_student_links psl ON u.id = psl.parent_id
            LEFT JOIN attendance_records ar ON psl.student_id = ar.student_id
            LEFT JOIN grades g ON psl.student_id = g.student_id
            WHERE u.id = ? AND u.tenant_id = ?
        ", [$parentId, $this->tenantId]);

        return [
            [
                'title' => 'Children Overview',
                'content' => "Children: {$stats['total_children']}\nAttendance Records: {$stats['total_attendance_records']}\nOverall Attendance Rate: " . round($stats['attendance_rate'] * 100, 1) . "%\nAverage Grade: " . round($stats['average_grade'], 1)
            ]
        ];
    }

    /**
     * Get accountant dashboard data
     */
    private function getAccountantDashboardData($filters)
    {
        $stats = db()->fetchOne("
            SELECT
                SUM(CASE WHEN status = 'paid' THEN amount ELSE 0 END) as total_income,
                SUM(CASE WHEN status = 'pending' THEN amount ELSE 0 END) as pending_payments,
                COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_invoices,
                COUNT(CASE WHEN status = 'overdue' THEN 1 END) as overdue_invoices
            FROM financial_records
            WHERE tenant_id = ? AND created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)
        ", [$this->tenantId]);

        return [
            [
                'title' => 'Financial Overview',
                'content' => "Total Income: $" . number_format($stats['total_income'], 2) . "\nPending Payments: $" . number_format($stats['pending_payments'], 2) . "\nPending Invoices: {$stats['pending_invoices']}\nOverdue Invoices: {$stats['overdue_invoices']}"
            ]
        ];
    }

    /**
     * Get librarian dashboard data
     */
    private function getLibrarianDashboardData($filters)
    {
        $stats = db()->fetchOne("
            SELECT
                COUNT(DISTINCT lb.id) as total_books,
                COUNT(DISTINCT CASE WHEN ll.status = 'active' THEN ll.id END) as borrowed_books,
                COUNT(DISTINCT CASE WHEN ll.status = 'active' AND ll.due_date < CURDATE() THEN ll.id END) as overdue_books,
                COUNT(DISTINCT CASE WHEN lb.status = 'available' THEN lb.id END) as available_books
            FROM library_books lb
            LEFT JOIN library_loans ll ON lb.id = ll.book_id
            WHERE lb.tenant_id = ?
        ", [$this->tenantId]);

        return [
            [
                'title' => 'Library Overview',
                'content' => "Total Books: {$stats['total_books']}\nBorrowed Books: {$stats['borrowed_books']}\nOverdue Books: {$stats['overdue_books']}\nAvailable Books: {$stats['available_books']}"
            ]
        ];
    }

    /**
     * Get transport dashboard data
     */
    private function getTransportDashboardData($filters)
    {
        $stats = db()->fetchOne("
            SELECT
                COUNT(DISTINCT tr.id) as total_routes,
                COUNT(DISTINCT tv.id) as total_vehicles,
                COUNT(DISTINCT CASE WHEN ta.status = 'active' THEN ta.id END) as assigned_students,
                COUNT(DISTINCT CASE WHEN ta.status = 'active' THEN ta.id END) - COUNT(DISTINCT CASE WHEN ta.status = 'active' THEN ta.id END) as unassigned_students
            FROM transport_routes tr
            LEFT JOIN transport_vehicles tv ON tr.vehicle_id = tv.id
            LEFT JOIN transport_assignments ta ON tr.id = ta.route_id
            WHERE tr.tenant_id = ? AND tr.is_active = 1
        ", [$this->tenantId]);

        return [
            [
                'title' => 'Transport Overview',
                'content' => "Active Routes: {$stats['total_routes']}\nActive Vehicles: {$stats['total_vehicles']}\nAssigned Students: {$stats['assigned_students']}\nUnassigned Students: {$stats['unassigned_students']}"
            ]
        ];
    }

    /**
     * Delete document
     */
    public function deleteDocument($documentId)
    {
        try {
            $document = $this->getDocument($documentId);

            if ($document && $document['file_path']) {
                $filePath = __DIR__ . '/../docs/' . $document['file_path'];
                if (file_exists($filePath)) {
                    unlink($filePath);
                }
            }

            db()->delete('ai_documents', 'id = ? AND tenant_id = ?', [$documentId, $this->tenantId]);

            return true;
        } catch (Exception $e) {
            error_log("AIDocumentationEngine::deleteDocument error: " . $e->getMessage());
            return false;
        }
    }
}
